## Numpy-3 : Creating Numpy Arrays - Basics

In [2]:
import numpy as np

**From built-in python containers (Lists, Tuples etc)**

In [3]:
# using list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
# using tuples
np.array((1, 2, 3, 4))

array([1, 2, 3, 4])

**Upcasting in Numpy**
- Upcasting in NumPy refers to the automatic conversion of data types when performing operations involving arrays of different types, so that no data is lost and the result has a compatible type that can hold all input values.

In [5]:
np.array([1, 2, 3.05])

array([1.  , 2.  , 3.05])

**Two Dimensional numpy array**

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

**Minimum dimensions 2**

In [7]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

**dtype**

In [8]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

**data consisting of more than one Data-type**

In [12]:
x = np.array([(1,2),(3,4.2)],dtype=[('a','i4'),('b',np.float32)])

In [13]:
x

array([(1, 2. ), (3, 4.2)], dtype=[('a', '<i4'), ('b', '<f4')])

In [14]:
x['a']

array([1, 3], dtype=int32)

In [15]:
x['b']

array([2. , 4.2], dtype=float32)

**np.asarray**

In [ ]:
np.array() => Always creates a new array (i.e., it copies data). Even if the input is already a NumPy array
np.asarray() => Just ensure object is a NumPy array

In [16]:
 a = [1, 2]

In [17]:
np.asarray(a)

array([1, 2])

In [18]:
a

[1, 2]

In [19]:
a = np.array([1, 2]) #Existing arrays are not copied

In [20]:
np.asarray(a) is a

True

**If dtype is set, array is copied only if dtype does not match:**

In [29]:
a = np.array([1, 2], dtype=np.float32)

In [30]:
np.asarray(a, dtype=np.float32) is a

True

In [31]:
a

array([1., 2.], dtype=float32)

In [21]:
np.asarray(a, dtype=np.float64) is a

False

**numpy.copy**

In [22]:
a

array([1, 2])

In [24]:
np.array(a, copy=True)  is a

False

In [25]:
np.array(a, copy=False)  is a

True

**Create an array x, with a reference y and a copy z**

In [26]:
x = np.array([1, 2, 3])

In [27]:
y = x

In [28]:
z = np.copy(x)

**when we modify x, y changes, but not z**

In [29]:
x[0] = 10

In [30]:
x

array([10,  2,  3])

In [31]:
y

array([10,  2,  3])

In [32]:
z

array([1, 2, 3])

**Read and write data from a file**

**Text Files (.txt, .csv)**

In [34]:
data = np.loadtxt("data.txt", delimiter=",")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [35]:
data = data ** 2
data

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [38]:
np.savetxt("output_data.txt", data,fmt="%d")

**Binary Files (.npy, .npz)**

In [39]:
arr = np.array([1, 2, 3, 4])
np.save("array.npy", arr)

In [40]:
arr = np.load("array.npy")
print(arr)

[1 2 3 4]


In [41]:
# Save multiple arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.savez("arrays.npz", arr1=a, arr2=b)

In [42]:
# Load them back
data = np.load("arrays.npz")
print(data["arr1"])  # [1 2 3]
print(data["arr2"])  # [4 5 6]

[1 2 3]
[4 5 6]


| File Format     | Read Function                | Write Function                   | Notes                               |
| --------------- | ---------------------------- | -------------------------------- | ----------------------------------- |
| `.txt` / `.csv` | `loadtxt()` / `genfromtxt()` | `savetxt()`                      | Use delimiter for custom separators |
| `.npy`          | `load()`                     | `save()`                         | For single array (binary)           |
| `.npz`          | `load()`                     | `savez()` / `savez_compressed()` | For multiple arrays                 |


**Advantages of .npy and .npz over Text Files**
| Feature                  | `.npy` / `.npz` (Binary)                            | `.txt` / `.csv` (Text)                          |
| ------------------------ | --------------------------------------------------- | ----------------------------------------------- |
| **Efficiency**        | Much faster to read/write                           | Slower I/O                                      |
| **Storage Size**      | More compact                                        | Larger file size                                |
| **Multiple Arrays**   | `.npz` can store many arrays in one file            | Not supported; need multiple files              |
| **No Parsing Needed** | Directly loads as NumPy array                       | Needs delimiter, dtype parsing                  |
| **More Reliable**     | No risk of formatting issues                        | Sensitive to extra spaces, missing values, etc. |


**numpy.fromfunction**

In [ ]:
#It constructs an array by calling a function on each coordinate/index of the desired shape.

In [69]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [71]:
iterable = (x*x for x in range(5)) #generator

In [72]:
iterable

<generator object <genexpr> at 0x00000218D20552F0>

In [73]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [74]:
#A new 1-D array initialized from text data in a string

In [75]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [76]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

**create a record array from a (flat) list of arrays**

In [44]:
x1 = [1, 2, 3]

In [45]:
x2 = [4.0, 5.0, 6.0] 

In [46]:
x3 = ['a', 'b', 'c']

In [49]:
list(zip(x1, x2, x3))

[(1, 4.0, 'a'), (2, 5.0, 'b'), (3, 6.0, 'c')]

In [86]:
r = np.array(list(zip(x1, x2, x3)), dtype=[('a', 'i4'), ('b', 'f4'), ('c', 'U1')])
print(r)
print(r['a'])


[(1, 4., 'a') (2, 5., 'b') (3, 6., 'c')]
[1 2 3]


**data types**

In [89]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [52]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")

#ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Dimension of this matrix: ",mat.ndim,sep='')

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2


In [51]:
#size gives the total number of elements
print("Size of this matrix: ", mat.size,sep='')

#shape gives the number of elements along each axes (dimension)
print("Shape of this matrix: ", mat.shape,sep='') 

#dtype gives the data type contained in the array
print("Data type of this matrix: ", mat.dtype,sep='') 

Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [53]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)

print("Data type of the modified matrix: ", mat.dtype,sep='') 
#dtype gives the data type contained in the array

Data type of the modified matrix: float64


In [54]:
b = np.array([(1.5,2,3), (4,5,6)])

print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


---