## Numpy-5 : Creating NumPy Arrays and Matrix Using Built-in Functions

**arange and linspace**

In [6]:
import numpy as np

`range(start, stop, step)`

`np.arange(start, stop, step, dtype)`

In [ ]:
help(np.arange)

In [4]:
list(range(5))

[0, 1, 2, 3, 4]

In [9]:
print("A series of numbers:",np.arange(5,16)) 
# A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [10]:
print("Numbers spaced apart by 2:",np.arange(0,12,2)) 
# Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [11]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) 
# Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [12]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


**np.linspace**

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`

In [102]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,10))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [13]:
np.linspace(1,5,10, dtype=np.int32)

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

**np.logspace()**

`np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)`

In [ ]:
np.linspace(start, stop) gives values evenly spaced in linear space.

np.logspace(start, stop) gives values evenly spaced in logarithmic space.

In [61]:
np.logspace(1, 2, 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [56]:
np.linspace(1, 1024, num=5, dtype = np.int32)

array([   1,  256,  512,  768, 1024], dtype=int32)

In [58]:
np.logspace(0, 10, num=5, base=2, dtype = np.int32) # [1,1024)

array([   1,    5,   32,  181, 1024], dtype=int32)

In [ ]:
# use case with learning rate => hyperparameter 
[0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0]

In [ ]:
# So on a log scale, equal distances represent equal ratios (e.g., x10), not equal differences.

In [118]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [119]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

**numpy array and matrix creation**

In [16]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [17]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [105]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [18]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
# The np.empty() function creates a new array of given shape and type, without initializing entries., 
# So the values in the array will be random garbage values (whatever happens to be in memory at the time).

In [23]:
print("Empty matrix\n-------------")
np.empty((4,5))

Empty matrix
-------------


array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23054293e-307, 8.45593934e-307],
       [7.56593017e-307, 1.33511290e-306, 8.90092016e-307,
        8.90104918e-307, 9.34602321e-307],
       [3.11525958e-307, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306],
       [1.29062229e-306, 1.24610383e-306, 1.33510679e-306,
        1.37961709e-306, 2.56765117e-312]])

**np.reshape()**

**Diagonal, Triangular, Lower Triangular and Upper Triangular Matrix**

In [ ]:
A triangular matrix is a square matrix where either:

All elements below the main diagonal are zero → Upper Triangular Matrix

All elements above the main diagonal are zero → Lower Triangular Matrix

A matrix must be square to be classified as triangular.

| Matrix Type      | Description              | Zeros are where? | NumPy function |
| ---------------- | ------------------------ | ---------------- | -------------- |
| Diagonal         | Only diagonal non-zero   | Off-diagonal     | `np.diag()`    |
| Lower Triangular | Zero above main diagonal | Above diagonal   | `np.tril()`    |
| Upper Triangular | Zero below main diagonal | Below diagonal   | `np.triu()`    |


In [28]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [29]:
print("Diagonal matrix:")
print(np.diag(np.diag(A)))

Diagonal matrix:
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [30]:
print("Lower triangular matrix:")
print(np.tril(A))

Lower triangular matrix:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [31]:
print("Upper triangular matrix:")
print(np.triu(A))

Upper triangular matrix:
[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [40]:
A = np.array([[1, 2, 3, 4],
              [4, 5, 6, 7],
              [7, 8, 9, 10]])

In [41]:
print(A.ndim, A.shape, A.dtype)

2 (3, 4) int64


In [42]:
print("Diagonal matrix:")
print(np.diag(np.diag(A)))

Diagonal matrix:
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [43]:
print("Lower triangular matrix:")
print(np.tril(A))

Lower triangular matrix:
[[1 0 0 0]
 [4 5 0 0]
 [7 8 9 0]]


In [44]:
print("Upper triangular matrix:")
print(np.triu(A))

Upper triangular matrix:
[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  9 10]]


**np.eye()**

In [ ]:
An identity matrix is a square matrix (same number of rows and columns) with:
- 1s on the main diagonal (top-left to bottom-right)
- 0s everywhere else

`np.eye(N, M=None, k=0, dtype=float, order='C')`

| Parameter | Description                                                                                 |
| --------- | ------------------------------------------------------------------------------------------- |
| `N`       | Number of rows (required)                                                                   |
| `M`       | Number of columns (optional, defaults to `N`)                                               |
| `k`       | Index of the diagonal:<br> `0` = main diagonal,<br> `1` = above main,<br> `-1` = below main |
| `dtype`   | Data type of output (default = `float`)                                                     |
| `order`   | `'C'` for row-major (default), `'F'` for column-major                                       |


In [46]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
mat1 = np.eye(3,4) 
print(mat1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**Extract a diagonal or construct a diagonal array.**

#### Diagonals in a Rectangular Matrix

Given a matrix **A** of size \( n * m \) (n rows, m columns):


#### What is a diagonal?

- The **main diagonal** runs from the top-left element \((0,0)\) to \((\min(n, m)-1, \min(n, m)-1)\).
- Other diagonals run parallel to the main diagonal, either above or below it.


#### Number of diagonals

- **Total diagonals** (including main diagonal):

\[
  total diagonals = n + m - 1
\]

- **Upper diagonals** (above main diagonal):

\[
m - 1
\]

- **Lower diagonals** (below main diagonal):

\[
n - 1
\]


#### Example

For a \(4 * 3\) matrix \((n=4, m=3)\):

- Total diagonals = \(4 + 3 - 1 = 6\)
- Upper diagonals = \(3 - 1 = 2\)
- Lower diagonals = \(4 - 1 = 3\)


#### Accessing diagonals in NumPy

Use `np.diag(A, k)` where:

- `k = 0`: main diagonal
- `k > 0`: k-th diagonal **above** main diagonal
- `k < 0`: k-th diagonal **below** main diagonal



In [62]:
print(np.arange(9))
print(100*"-")
print(np.arange(9).reshape((3,3)))

[0 1 2 3 4 5 6 7 8]
----------------------------------------------------------------------------------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
x = np.arange(9).reshape((3,3))

In [64]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
np.diag(x)

array([0, 4, 8])

In [125]:
np.diag(x, k=1)

array([1, 5])

In [126]:
np.diag(x, k=-1)

array([3, 7])

In [127]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

**NumPy allows triangular functions like `np.tril()` and `np.triu()` to operate on rectangular matrices for flexibility and general-purpose use — even though the strict mathematical definition of triangular matrices only applies to square matrices.**



In [128]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [68]:
np.tri(3, 5, 0, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [130]:
np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
#return a Lower triangle of an array.

In [69]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
np.tril(arr, -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [132]:
#return Upper triangle of an array.

In [71]:
np.triu(arr, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

**Random number generation**

1. Uniform Distribution : Occurence of value 1 to 6 if a die is rolled 10,000 times
2. Normal Distribution : Height of person in india for a sample of 1 Million People

In [72]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) 
# 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

Random number generation (from Uniform distribution)
[[0.07555202 0.09988798 0.84163818]
 [0.81425217 0.20967887 0.12520277]]


In [73]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.22912484  1.71437712 -1.0000993 ]
 [-0.8236714   0.24857661 -0.26972985]
 [ 1.68099442 -0.77396406  0.37860004]
 [ 0.59336717 -0.31427903  0.4722494 ]]


In [74]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: [74 16 54 89 14 68  8 17 26 19]

Random integer matrix


In [75]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[96  8 16 60]
 [44 22 35 13]
 [ 2 29 73 94]
 [19 83 12 44]]

20 samples drawn from a dice throw: [3 4 6 3 5 4 3 5 3 1 5 4 5 6 5 1 1 5 5 6]


---