## Numpy-10 : Built-In Functions - (ravel, moveaxis, squeeze, concatenate, stack, split, tile, repeat, append, unique)

In [4]:
#import 
import numpy as np
from numpy.random import randint as ri

In [5]:
a = np.arange(6).reshape(3,2)

In [6]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

**1. ravel()**
- ravel() is a NumPy method used to flatten a multi-dimensional array into a 1D array.
- It returns a view of the original array whenever possible (i.e., it does not copy data unless necessary).

In [7]:
# help
help(np.ravel)

Help on _ArrayFunctionDispatcher in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changi

In [8]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
np.ravel(a) # row major order

array([0, 1, 2, 3, 4, 5])

In [10]:
# Row-major (C-style, last axis changes fastest)
np.ravel(a, order ='C')

array([0, 1, 2, 3, 4, 5])

In [11]:
# Column-major (Fortran-style, first axis changes fastest)
np.ravel(a, order ='F')

array([0, 2, 4, 1, 3, 5])

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
#reshape
a.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [17]:
#flatten
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [18]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
temp = np.ravel(a)
temp

array([0, 1, 2, 3, 4, 5])

In [20]:
# reshape
np.reshape(temp, (3, 2)) # row major

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
 # Fortran-like index ordering => Column-major
np.reshape(temp, (3, 2), order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
"""
Difference between ravel() and flatten()
    - ravel() flattens the array to 1D.
    - Returns a view if possible, else returns a copy.
    - Faster than flatten() because it avoids copying when possible.
"""

| Feature                                | `ravel()`          | `flatten()`               |
| -------------------------------------- | ------------------ | ------------------------- |
| **Returns**                            | View (if possible) | Always returns a **copy** |
| **Memory Efficient**                   | ✅ Yes              | ❌ No                      |
| **Modifying result affects original?** | Yes (if view)      | No (copy is separate)     |


---

**View**
- When you create a view (via slicing, reshape, transpose, etc.):
- NumPy does NOT copy the data.
- Instead, it creates a new ndarray object that have a separate(shape, strides etc) metadata but Points to the same data buffer


In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
view = arr[1:5:2]  # selects [20, 40]

In [23]:
view

array([20, 40])

In [24]:
view[0]= 123

In [25]:
arr

array([ 10, 123,  30,  40,  50,  60])

In [26]:
np.shares_memory(arr, view) # True → it's a view

True

---

**2. moveaxis()**
- np.moveaxis() is used to reorder axes in a NumPy array by moving specific axes to new positions, while keeping the order of the other axes the same.
-  Returns a view of the array with moved axes.

In [27]:
x = np.zeros((3, 4, 5))
print(x)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [28]:
print(x.shape) # (3, 4, 5) => (4,5,3)

(3, 4, 5)


In [29]:
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [31]:
print(x.shape)
np.moveaxis(x, [0, 1], [-1, -2]).shape

(3, 4, 5)


(5, 4, 3)

**3. Squeeze()**
- The np.squeeze() function removes axes of length 1 (i.e., singleton dimensions) from an array.
- Returns a view of the array with moved axes.

In [32]:
x = np.array([[[0], [1], [2]]])

In [33]:
x

array([[[0],
        [1],
        [2]]])

In [34]:
x.shape

(1, 3, 1)

In [36]:
np.squeeze(x).shape

(3,)

In [39]:
np.squeeze(x, axis=2).shape

(1, 3)

**4. concatenate()**
- In NumPy, concatenate() is used to join two or more arrays along an existing axis.

In [ ]:
#Join a sequence of arrays along an existing axis

In [40]:
a = np.array([[1, 2], [3, 4]])

In [41]:
b = np.array([[5, 6]])

In [42]:
a.shape

(2, 2)

In [43]:
b.shape

(1, 2)

In [51]:
# default axis=0
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
# dimension will increase along axis 0
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a.shape

(2, 2)

In [53]:
b.T.shape

(2, 1)

In [55]:
# dimension will increase along axis 0
np.concatenate((a, b.T), axis=1).shape

(2, 3)

**5. stack()**
- In NumPy, stack() is used to join a sequence of arrays along a new axis — unlike concatenate() which joins along an existing axis.

In [56]:
a = np.array([[1, 2, 3]])

In [57]:
b = np.array([[2, 3, 4]])

In [58]:
a.shape

(1, 3)

In [59]:
b.shape

(1, 3)

In [61]:
# default axis
np.stack((a,b)).shape

(2, 1, 3)

In [62]:
# axis 0
np.stack((a,b),axis=0).shape

(2, 1, 3)

In [64]:
# axis 1
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [2, 3, 4]]])

In [65]:
# hstack()
np.hstack((a,b)) # stack() axis=1

array([[1, 2, 3, 2, 3, 4]])

In [66]:
# vstack()
np.vstack((a,b)) # stack() axis=0

array([[1, 2, 3],
       [2, 3, 4]])

In [67]:
# dstack()
np.dstack((a,b)) # stack() axis=2

array([[[1, 2],
        [2, 3],
        [3, 4]]])

**split()**
- In NumPy, the split() function is used to divide an array into multiple sub-arrays.

In [68]:
import numpy as np

In [69]:
# split an array multiple sub-arrays

In [70]:
x = np.arange(12.0)

In [71]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [72]:
np.split(x, [3, 10])

[array([0., 1., 2.]), array([3., 4., 5., 6., 7., 8., 9.]), array([10., 11.])]

In [ ]:
#multiple splits based on 3rd axis

In [73]:
x = np.arange(16.0).reshape(2, 2, 4)

In [74]:
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [75]:
x.shape

(2, 2, 4)

In [77]:
np.split(x, 2, axis=2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [78]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [80]:
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [81]:
x.shape

(2, 2, 4)

In [82]:
np.split(x, 2, axis=1)

[array([[[ 0.,  1.,  2.,  3.]],
 
        [[ 8.,  9., 10., 11.]]]),
 array([[[ 4.,  5.,  6.,  7.]],
 
        [[12., 13., 14., 15.]]])]

In [83]:
np.hsplit(x, 2) # horizontal split

[array([[[ 0.,  1.,  2.,  3.]],
 
        [[ 8.,  9., 10., 11.]]]),
 array([[[ 4.,  5.,  6.,  7.]],
 
        [[12., 13., 14., 15.]]])]

In [86]:
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [87]:
x.shape

(2, 2, 4)

In [84]:
np.split(x, 2, axis=0)

[array([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]]),
 array([[[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]])]

In [88]:
np.vsplit(x, 2) # vertical split

[array([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]]),
 array([[[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]])]

**tile()**
- np.tile() is used to repeat an array along specified axes to create a larger array by tiling (tiling = like tiling a floor).

In [92]:
x.shape

(2, 2, 4)

In [93]:
np.tile(x, 2)

array([[[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 12., 13., 14., 15.]]])

**repeat()**
- np.repeat() is used to repeat each element of an array(elementwise), not the whole array like np.tile()(arraywise)).

In [94]:
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [97]:
np.repeat(x, 2,axis=2)

array([[[ 0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.],
        [ 4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.]],

       [[ 8.,  8.,  9.,  9., 10., 10., 11., 11.],
        [12., 12., 13., 13., 14., 14., 15., 15.]]])

**append()**
- numpy.append() is used to append values to the end of an array, creating a new array with the added elements.
- `numpy.append(arr, values, axis=None)`

In [98]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**unique()**
- In NumPy, the np.unique() function is used to find the unique elements of an array.

In [99]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [100]:
np.unique([[1, 1], [2, 3]])

array([1, 2, 3])

In [101]:
np.unique([[1, 1], [2, 3]], axis=0)

array([[1, 1],
       [2, 3]])

In [102]:
np.unique([[1, 1], [1, 1], [2, 3]], axis=0)

array([[1, 1],
       [2, 3]])

### Congratulations !! That's the end of Conceptual and Syntax Part of NumPy. 
### Will do Some end-to-end project from next Lecture.